subscribers:

    camera_2d:
        topic: /d400/color/image_raw          # Image Topic

    camera_3d:
        topic: /d400/aligned_depth_to_color/image_raw  # Depth map Topic

    camera_3d_info:
        topic: /d400/depth/camera_info    # Depth map info Topic

    synchronized_queue_size: 20             # number of frames to consider synchronizing
                                            # via ApproximateTimeSynchronizer

    absoulte_synchronized_time_diff: 0.2    # max delay between timestamp of 
                                            # image and depthimage topics

enable_debug_image: True

publishers:

    # debug_image only published if enable_debug_image is True
    debug_image:
        topic: /object_detector/debug/image_raw
        queue_size: 1

    detected_objects:
        topic: /object_detector/detected
        queue_size: 1

    objects_markers:
        topic: /object_detector/markers
        queue_size: 1

camera_frame_id: d400_depth_optical_frame

subsampling: 10
